 version: "2"         # required to adjust maintainability checks
 plugins:
  sonar-java:
    enabled: false
  pmd:
    enabled: true
    config:
      file: pmd-rules.xml
  checkstyle:
    enabled: true
