# This is a basic workflow to help you get started with Actions

name: CodeQuality

# Controls when the workflow will run
on: [push]

jobs:
  codeQuality:
    runs-on: ubuntu-latest
    # container:
    #  image: registry.gitlab.com/billyan2018/codeclimate-lite
    steps:  
    - uses: actions/checkout@v2
    - id: file_changes
      uses: trilom/file-changes-action@v1
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: test
      run: |
          ls $HOME
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_deleted.json
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_deleted}}'
    - name: code scan
      run: |
         pwd && ls -l && \
         start=`date +%s` \
         && export SOURCE_CODE="$PWD" \
         && export REPORT_FORMAT="json" \
         && /usr/bin/docker run \
         --volume "$SOURCE_CODE":/code \
          --volume /tmp/cc:/tmp/cc \
         registry.gitlab.com/billyan2018/codeclimate-lite analyze -f "$REPORT_FORMAT" > "raw_codeclimate.$REPORT_FORMAT" \
         && end=`date +%s` && runtime=$((end-start)) && echo $runtime 
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-quality-report
        path: raw_codeclimate.json
    
