name: CodeQuality

on: [push]

jobs:
  codeQuality:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Set fetch-depth: 0 to fetch all history for all branches and tags.
    - name: run git diff
      run: |
         git fetch origin master 
         echo "------"
         echo "$( git diff --name-only origin/master...)"
         echo "===="
         echo "::set-output name=changedFiles :: $( git diff --name-only origin/master...)"
      id: git-diff
    - name: List all modified files
      run: | 
          for file in "${{ steps.git-diff.outputs.changedFiles }}"; do
            echo "$file was modified"
          done
    - name: code scan
      run: |
         pwd && ls -l && \
         start=`date +%s` \
         && export SOURCE_CODE="$PWD" \
         && export REPORT_FORMAT="json" \
         && /usr/bin/docker run \
         --volume "$SOURCE_CODE":/code \
          --volume /tmp/cc:/tmp/cc \
         registry.gitlab.com/billyan2018/codeclimate-lite analyze -f "$REPORT_FORMAT" > "raw_codeclimate.$REPORT_FORMAT" \
         && end=`date +%s` && runtime=$((end-start)) && echo $runtime 
    - name: Only keep issues in changed files
      run: |
         /usr/bin/docker run --entrypoint /usr/bin/node \
         --volume "$PWD":/code \
         registry.gitlab.com/billyan2018/codeclimate-lite  "/usr/src/app/report-processor/main.js" ${{steps.git-diff.outputs.changedFiles}}
    - name: Archive code quality report
      uses: actions/upload-artifact@v2
      with:
        name: code-quality-report
        path: 'raw_codeclimate.json'
    - name: Archive changed code quality
      uses: actions/upload-artifact@v2
      with:
        name: code-quality-report
        path: 'changed_codeclimate.json'
    
