name: CodeQuality

on:
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build jar
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs
  
  codeQuality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Set fetch-depth: 0 to fetch all history for all branches and tags.
    - name: code scan
      run: |
         docker run    --rm    \
         --volume /tmp:/tmp \
         --volume "$PWD":/home/linter/code registry.gitlab.com/billyan2018/lite-linter:latest  \
         && cp /tmp/gl-code-quality-report.json .
    - name: Archive code quality report
      uses: actions/upload-artifact@v2
      with:
        name: code-quality-report
        path: |
          gl-code-quality-report.json

