name: CodeQuality

on:
  pull_request:
    branches:
      - '**'

jobs:
  codeQuality:
    runs-on: ubuntu-latest
    steps:  
    - name: changed lines
      id: changed-lines
      uses: billyan2018/codeclimate-changed@0.6
      with:
        token: ${{ github.token }}


    
