name: CodeQuality

on: [push]

jobs:
  codeQuality:
    runs-on: ubuntu-latest
    steps:  
    - name: change lines
      id: changed-lines
      uses: billyan2018/codeclimate-changedlines@0.4


    
